### ISSUE TITLE
Issue to create a grid area : select grid type

### ISSUE THREAD

**Issue by claramoret** [AntonelloDN/Envimet-inx#2]
Hello ! 

I am writing with regard to a problem with the plug-in SketchUp Envimet-INX. 
 
I download the extension without issue and follow the video tutorial here : https://www.youtube.com/watch?time_continue=2&v=_p_aVIDoQQg&feature=emb_title. 
 
I have the problem at 4:10 of the video. When I created a grid area in sketch up and I want to select grid type : 1 / 2 / 3, it appears a message saying: "invalid integer", even though I'm pressing the "3" option + enter. 

![problem sketchup](https://user-images.githubusercontent.com/71373855/93307738-9fed3480-f801-11ea-97ff-611236dd9a92.JPG)

 So I can't create a grid area and use the extension.
Could you tell me how I can create the grid area correctly ? 

Thank you for your help, 

Clara

**Comment by AntonelloDN** [comment]
Hi @claramoret,

It is not compatible with SKP 2017. Could you test it with SKP 2019 or SKP 2020?

Best,
Antonello

**Comment by claramoret** [comment]
Hi, 

Thank you for your help, it works with the Pro version.

But I have one another problem. I followed your video tutorial again. When I want to create a INX file (the final step!), a message appeared. 

![Capture](https://user-images.githubusercontent.com/71373855/93483076-b5955380-f900-11ea-9e38-87d45adbc3ad.JPG)

Do you know what can be the problem ?

Thank you

Clara

**Comment by claramoret** [comment]
I just see the solution in the old issue. 

I can't create the INX file if i'm using the location with the icon at the bottom left corner of the SKP interface.
I am now able to save the file in INX format and able to open the same in ENVI MET.

Thanks for your support.

Clara

**Comment by AntonelloDN** [comment]
@claramoret I close this issue. If you have this kind of issue again I can open it again.

**Comment by ParaniAmal** [comment]
I am experiencing the same issue; May i know, how did you resolve that?
