### ISSUE TITLE
Modifications of the project impossible after closing the file 

### ISSUE THREAD

**Issue by claramoret** [AntonelloDN/Envimet-inx#3]
Hello, 

I have got a problem with the file SKPINX, I can't open a new after saving the model in SKPINX and closing the file. The file saving in SKPINX isn't recognize as a SKP file.
Also, I can't make modifications to my project with the file saving in SKP file also. I can open the file, but I can't create a new Envimet building, a error message appears "please create a envimet grid first". The Envimet grid is already created, I can see it, but it isn't active. 

Could you help me for this problem ?

Thank you for your help.

**Comment by AntonelloDN** [comment]
Hi @claramoret ,

useful info:
- skpinx is like a db for envimet properties only
- skp file is like a db for referenced geometries only
- inx is the output file of envimet

I will change this behavior in the future.

If you have to open the model again you should:
1. open skp file
2. import skpinx file using this command here: ![image](https://user-images.githubusercontent.com/16763953/93996516-a7c54f80-fd92-11ea-95c0-255c3caa0729.png)
3. check with info command of envimet toolbar if envimet properties are imported
4. if everithing is Ok, you can continue updating your model (adding, deleting and so on)

Important:
if you change something rember to save again following this order (see [wiki](https://github.com/AntonelloDN/Envimet-inx/wiki/01.-Create-your-first-model-with-Envimet-INX#save-skp-skpinx-inx)):
1. SKP
2. SKPINX
3. INX

Please, let me know if it clear and if it works.

Antonello

**Comment by claramoret** [comment]
Hi Antonello, 

Thank you for yours explanations, I understand and it works !! 

Clara

**Comment by AntonelloDN** [comment]
@claramoret it is my pleasure. I close this issue. Thanks for your feeback.
