### ISSUE TITLE
Soil elements no appeared in the Envimet file

### ISSUE THREAD

**Issue by claramoret** [AntonelloDN/Envimet-inx#5]
Hello Antonello, 

I have got a new problem : I can't see the soil elements in the Envim-met input. 

I done some tests according the size of elements. The problem is the same. 

Can you see what is the problem ?

Thank you for your help.

Clara

**Comment by AntonelloDN** [comment]
Hi @claramoret ,

Could you try to:
1. Delete envimet soils object
2. Extrude them a bit
3. Make them again like envimet soils

Best,
Antonello

**Comment by claramoret** [comment]
Hello Antonello, 

I tried with a simple shape (surface or volum), or complex one, it's the same problem everytime.

Clara

**Comment by AntonelloDN** [comment]
Thanks for your test. Could you send me the file? If you want by email.

**Comment by AntonelloDN** [comment]
Thanks @claramoret, I close this issue
